getevidence/getevidence/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='base.html')),

    # Examples:
    # url(r'^$', 'getevidence.views.home', name='home'),
    # url(r'^getevidence/', include('getevidence.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin', include(admin.site.urls)),

    url(r'variant', include('variants.urls', namespace="variants")),
)

getevidence/variants/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^/?$', views.index, name='index'),
    url(r'^/new/?$', views.new, name='new'),
    url(r'^/(.+)/edit/?$', views.edit, name='edit'),
    url(r'^/(.+)/add_pub/?$', views.add_pub, name='add_pub'),
    url(r'^/(.+)/?$', views.detail, name='detail'),
)

getevidence/variants/models.py
"""
==============
Variant models
==============

DbSNP:         Information for a dbSNP entry
Variant:       Tracks immutable variant data
VariantReview: Tracks user-editable data for a variant

"""

import re
import reversion
from django.db import models
from genes.models import Gene
from publications.models import Publication


class DbSNP(models.Model):
    """Contains dbSNP information.

    dbSNP IDs are a separate class with a many-to-many mapping because
    (1) some variants have multiple dbSNP IDs mapped to the same
    location, (2) dbSNP IDs refer to a position and some have more
    than two alleles (e.g. triallelic)

    Data attributes:
    rsid: dbSNP identifier (CharField, unique)

    """

    rsid = models.CharField(max_length=16, unique=True)

    def __unicode__(self):
        """Returns string with dbSNP identifier."""
        return self.rsid


class Variant(models.Model):
    """Tracks immutable variant data.
    
    Data attributes:
    gene:         Gene from genes.models
    aa_reference: amino acid(s) for reference it this position
    aa_position:  position of amino acid variant
    aa_variant:   variant amino acid(s) at this position
    dbsnps:       DbSNP (ManyToManyField)
    
    The combination of gene, aa_reference, aa_position, and aa_variant 
    is required to be unique.

    """
    # Regex validates and parses strings representing variants.
    VARIANT_RE = r'^([A-Z0-9]+)-([A-Z]+)([0-9]+)([A-Z]+)$'

    # Combination of gene and amino acid change uniquely define Variant.
    gene = models.ForeignKey(Gene)
    aa_reference = models.CharField(max_length=10,
                                    verbose_name='reference amino acid')
    aa_position = models.IntegerField(verbose_name='amino acid position')
    aa_variant = models.CharField(max_length=10,
                                  verbose_name='variant amino acid')

    # ManyToMany because dbSNP entries can be duplicate or tri-allelic.
    dbsnps = models.ManyToManyField(DbSNP)

    @classmethod
    def create(cls, gene_name=None, aa_ref=None, aa_pos=None, aa_var=None):
        gene = Gene.objects.get(hgnc_symbol=gene_name)
        variant = cls(gene = gene,
                      aa_reference = aa_ref,
                      aa_position = aa_pos,
                      aa_variant = aa_var)
        variant.save()
        variantreview = VariantReview(variant = variant)
        variantreview.save()
        return variant

    @classmethod
    def remove(cls, variant=None):
        varrev = VariantReview.objects.get(variant=variant)
        varrev.delete()
        variant.delete()

    @classmethod
    def parse_variant(cls, variant_string):
        """Parse variants identified by gene and amino acid change.

        Examples: HBB-E7V, APOE-C130R

        The first part before the dash is the HGNC gene symbol.
        After the dash is the reference amino acid, the amino acid position,
        and the variant amino acid.
        """
        assert re.match(cls.VARIANT_RE, variant_string)
        parsed = re.match(cls.VARIANT_RE, variant_string).groups()
        return { 'gene_name': parsed[0],
                 'aa_ref': parsed[1],
                 'aa_pos': int(parsed[2]),
                 'aa_var': parsed[3],
                 }

    @classmethod
    def variant_lookup(cls, variant_string):
        """Find and return Variant in database matching identifying string."""
        var_parse = cls.parse_variant(variant_string)
        var_match = cls.objects.get(
            gene__hgnc_symbol__exact=var_parse['gene_name'],
            aa_reference__exact=var_parse['aa_ref'],
            aa_position__exact=var_parse['aa_pos'],
            aa_variant__exact=var_parse['aa_var'],
            )
        return var_match

    class Meta:
        """Defines combination of gene and amino acid change as unique."""
        unique_together = (('gene', 'aa_reference', 
                            'aa_position', 'aa_variant'),)

    def __unicode__(self):
        """Returns string with gene name and amino acid change."""
        return (self.gene.hgnc_symbol + '-' + self.aa_reference +
                str(self.aa_position) + self.aa_variant)

    name = property(__unicode__)


class VariantReview(models.Model):
    """Tracks user-editable data for a variant.

    Non-editable data attributes:
    variant:                Variant (OneToOneField)

    Editable data attributes:
    review_summary:         interpretation summary (CharField)
    review_long:            extended interpretation (CharField)
    impact:                 impact (pathogenic, benign, etc) (CharField)
    inheritance:            inheritance (recessive, dominant, etc) (CharField)
    evidence_computational: computational evidence score (SmallIntegerField)
    evidence_functional:    functional evidence score (SmallIntegerField)
    evidence_casecontrol:   case/contral evidence score (SmallIntegerField)
    evidence_familial:      familial evidence score (SmallIntegerField)
    clinical_severity:      clinical severity score (SmallIntegerField)
    clinical_treatability:  clinical treatability score (SmallIntegerField)
    clinical_penetrance:    genetic penetrance score (SmallIntegerField)
    publications:           Publication (ManyToManyField through
                                         VariantPublicationReview)
    """
    variant = models.OneToOneField(Variant, editable=False)

    review_summary = models.TextField(blank=True)
    review_long = models.TextField(blank=True)
    impact_choices = (('ben', 'benign'),
                      ('pat', 'pathogenic'),
                      ('pha', 'pharmacogenetic'),
                      ('pro', 'protective'),
                      ('not', 'not reviewed'))
    impact = models.CharField(max_length=3,
                              choices=impact_choices,
                              default='not' )
    inheritance_choices = (('dom', 'dominant'),
                           ('rec', 'recessive'),
                           ('oth', 'other'),
                           ('und', 'undefined in literature'),
                           ('unk', 'unknown or not review'))
    inheritance = models.CharField(max_length=3,
                                   choices=inheritance_choices,
                                   default='unk' )

    # Define evidence and clinical importance scores.
    SCORE_CHOICES = ( (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5) )
    evidence_computational = models.SmallIntegerField(null=True,
                                                      blank=True,
                                                      choices=SCORE_CHOICES)
    evidence_functional = models.SmallIntegerField(null=True,
                                                   blank=True,
                                                   choices=SCORE_CHOICES)
    evidence_casecontrol = models.SmallIntegerField(null=True,
                                                    blank=True,
                                                    choices=SCORE_CHOICES)
    evidence_familial = models.SmallIntegerField(null=True,
                                                 blank=True,
                                                 choices=SCORE_CHOICES)
    clinical_severity = models.SmallIntegerField(null=True,
                                                 blank=True,
                                                 choices=SCORE_CHOICES)
    clinical_treatability = models.SmallIntegerField(null=True,
                                                     blank=True,
                                                     choices=SCORE_CHOICES)
    clinical_penetrance = models.SmallIntegerField(null=True,
                                                   blank=True,
                                                   choices=SCORE_CHOICES)
    # Define publications as ManyToMany through VariantPublicationReview
    publications = models.ManyToManyField(Publication,
                                          through='VariantPublicationReview')

    def __unicode__(self):
        """Returns text containing long variant review."""
        return self.review_summary


class VariantPublicationReview(models.Model):
    """Tracks user-editable variant-specific publication reviews.

    Data attributes:
    variant:       Variant
    publication:   Publication from publications.models
    summary:       review of publication's info regarding variant (TextField)

    """
    variantreview = models.ForeignKey(VariantReview)
    publication = models.ForeignKey(Publication)
    summary = models.TextField()

    class Meta:
        """Defines combination of variant and publication as unique."""
        unique_together = (('variantreview', 'publication',))

    def __unicode__(self):
        """Returns string containing variant, publication, and summary."""
        return str(self.publication) + ',' + str(self.variantreview.variant) + ':' + self.summary

    @classmethod
    def create(cls, variantreview=None, pmid=None):
        try:
            pub = Publication.pub_lookup(pmid)
        except Publication.DoesNotExist:
            pub = Publication.create(pmid=pmid)
            pub.save()
        varpubreview = cls(variantreview=variantreview, publication=pub)
        varpubreview.save()
        return varpubreview


# Register models with reversion.
reversion.register(VariantReview)
reversion.register(VariantPublicationReview)
reversion.register(Variant)

getevidence/variants/forms.py
import re
from django import forms
from .models import Gene, Variant, VariantReview, VariantPublicationReview

class VariantReviewForm(forms.ModelForm):
    class Meta:
        model = VariantReview
        fields = ('review_summary',
                  'review_long',
                  'impact',
                  'inheritance',
                  'evidence_computational',
                  'evidence_functional',
                  'evidence_casecontrol',
                  'evidence_familial',
                  'clinical_severity',
                  'clinical_treatability',
                  'clinical_penetrance',
                  )

        widgets = {
            'review_summary': forms.Textarea(attrs={'class': 'span10 lead',
                                                    'rows': 3}),
            'review_long': forms.Textarea(attrs={'class': 'span10',
                                                 'rows': 8})
            }


class AddVarPubReviewForm(forms.Form):
    pmid = forms.IntegerField(min_value=1)


class NewVariantForm(forms.Form):
    gene = forms.CharField()
    aa_reference = forms.CharField()
    aa_position = forms.IntegerField(min_value=1)
    aa_variant = forms.CharField()

    def clean_gene(self):
        try:
            gene = Gene.objects.get(hgnc_symbol=self.cleaned_data['gene'])
            return self.cleaned_data['gene']
        except Gene.DoesNotExist:
            raise forms.ValidationError('No gene in database with gene symbol "' +
                                        self.cleaned_data['gene'] + '".')

    def clean_aa_reference(self):
        single_letter = '[ACDEFGHIKLMNPQRSTVWY]'
        if re.match('^(' + single_letter + '+|[X\*])$', self.cleaned_data['aa_reference']):
            return self.cleaned_data['aa_reference']
        else:
            raise forms.ValidationError('aa_reference ("' +
                                        self.cleaned_data['aa_reference'] +
                                        '") must be a string consisting of ' +
                                        'one or more amino acids, in single letter code.')

    def clean_aa_variant(self):
        single_letter = '[ACDEFGHIKLMNPQRSTVWY]'
        if re.match('^(' + single_letter + '+|[X\*])$', self.cleaned_data['aa_variant']):
            return self.cleaned_data['aa_variant']
        else:
            raise forms.ValidationError('aa_variant ("' +
                                        self.cleaned_data['aa_variant'] +
                                        '") must be a string consisting of ' +
                                        'one or more amino acids, in single letter code.')

getevidence/variants/templates/variants/detail.html
{% extends "variants/index.html" %}

{% load variants_extras %}

{% block page_title %}
<div class="row-fluid">
  <div class="span10">
    {{ variant.name }}
  </div>
  <div class="span2">
    {% block variant_edit_button %}<a class="btn btn-primary btn-large" href="{% url 'variants:edit' variant.name %}">Edit variant</a>{% endblock variant_edit_button %}
  </div>
</div>
{% endblock page_title %}

{% block content %}
<div class="row">
  <div class="span10 lead">
    {{ variantreview.review_summary }}
  </div>
  <div class="span2 muted">
    HGNC ID: <A HREF="http://http://www.genenames.org/data/hgnc_data.php?hgnc_id={{ variant.gene.hgnc_id }}">{{ variant.gene.hgnc_id }} <i class="icon-external-link-sign"></i></A>
    <br />
    NCBI Gene ID: <A HREF="http://www.ncbi.nlm.nih.gov/gene/{{ variant.gene.ncbi_gene_id }}">{{ variant.gene.ncbi_gene_id }} <i class="icon-external-link-sign"></i></A>
    {% if variant.gene.mim_id %}
    <br />
    OMIM: <A HREF=http://omim.org/entry/{{ variant.gene.mim_id }}>{{variant.gene.mim_id}} <i class="icon-external-link-sign"></i></A>
    {% endif %}
    {% if variant.gene.clinical_testing %}
    <br />
    <A HREF="http://www.ncbi.nlm.nih.gov/gtr/genes/{{ variant.gene.ncbi_gene_id }}/">Genetic Testing Reg. <i class="icon-external-link-sign"></i></A>
    {% endif %}
    {% if variant.gene.acmg_recommended %}
    <br />
    <b> ACMG recommended </b>
    {% endif %}
    <br />
  </div>
</div>

<div class="row">
  <div class="span6">
    <h3>Evidence</h3>
    <table class="table table-condensed">
      <tr>
	<td><h5 style="margin:0">Computational</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.evidence_computational %}</td>
      </tr>
      <tr>
	<td><h5 style="margin:0">Functional</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.evidence_functional %}</td>
      </tr>
      <tr>
	<td><h5 style="margin:0">Case/control</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.evidence_casecontrol %}</td>
      </tr>
      <tr>
	<td><h5 style="margin:0">Familial</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.evidence_familial %}</td>
      </tr>
    </table>
  </div>
  <div class="span6">
    <h3>Clinical impact</h3>
    <table class="table table-condensed">
      <tr>
	<td><h5 style="margin:0">Severity</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.clinical_severity %}</td>
      </tr>
      <tr>
	<td><h5 style="margin:0">Treatability</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.clinical_treatability %}</td>
      </tr>
      <tr>
	<td><h5 style="margin:0">Penetrance</h5></td>
	<td>{% include "variants/score_display.html" with score=variantreview.clinical_penetrance %}</td>
      </tr>
    </table>
  </div>
</div>

<hr />

<div class="row">
  <div class="span6">
    <h4>Impact</h4>
    <p>{{ variantreview.get_impact_display }}</p>
  </div>
  <div class="span6">
    <h4>Inheritance</h4>
    <p>{{ variantreview.get_inheritance_display }}</p>
  </div>
</div>

<hr />

<h4>Long review</h4>
<p style="white-space:pre-wrap;">{{ variantreview.review_long }}</p>

<hr />

<h4>Additional data</h4>
<p>
dbSNP: {{ dbsnps|join:", " }}
</p>

<h4>Revisions</h4>
<ul>
{% for version in variantreview_history %}
<li><strong>{{ version.revision.date_created }}:<strong> {{ version.field_dict|get_item:"review_summary" }}</li>
{% endfor %}
</ul>

<hr />

<h3> Publications </h3>

<ul>
{% for varpubreview in varpubreviews %}
<li>
  <p>{{ varpubreview.publication.author_list }} <strong>"{{ varpubreview.publication.title }}"</strong> {{ varpubreview.publication.journal }}. {{ varpubreview.publication.pub_date }}; {{ varpubreview.publication.journal_location }}. PMID: <A HREF=http://www.ncbi.nlm.nih.gov/pubmed/{{ varpubreview.publication.pmid }}>{{ varpubreview.publication.pmid }} <i class="icon-external-link-sign"></i></A></p>
  <div class="well"><small><strong>Abstract: </strong>{{ varpubreview.publication.abstract }}</small></div>
  <p>{{ varpubreview.summary }}</p>
</li>
{% endfor %}
</ul>

<div class="addpub_button">
  <p>
    <button class="btn">Add publication</button>
  </p>
</div>

<div class="addpub_form">
  <form class action="{% url 'variants:add_pub' variant.name %}" method="post">
    {% csrf_token %}
    <label for="id_pmid">Pubmed ID:</label>
    {{ addvarpubreview_form.pmid }}
    <p><input type="submit" value="Submit" /></p>
  </form>
</div>
{% endblock content %}


{% block extra_js %}
<script>
  $(function() {
    console.log("loading script")
    $(".addpub_form").hide();
    $(".addpub_button").click(function() {
      $(".addpub_button").hide();
      $(".addpub_form").show();
    });
  });
</script>
{% endblock extra_js %}

getevidence/variants/templates/variants/edit.html
{% extends "variants/detail.html" %}

{% block variant_edit_button %}{% endblock variant_edit_button %}

{% block content %}
<form class="form-vertical editor span12" action="{% url 'variants:edit' variant.name %}" method="post">
{% csrf_token %}
{{ form }}
<br/>
<input class="btn btn-primary btn-large" type="submit" value="Submit" />
</form>
{% endblock content %}

getevidence/variants/templates/variants/index.html
{% extends "base.html" %}

{% block navbar_list %}
<li class="active"><a href="/variant">Variants</a></li>
{% endblock navbar_list %}

{% block page_title %}Variants{% endblock page_title %}

{% block content %}
{% if variant_list %}
<div class="row">
<table class="table span6 table-hover">
  {% for variant in variant_list %}
  <tr><td><a href="{% url 'variants:detail' variant.name %}">{{ variant.name }}</a></td></tr>
{% endfor %}
</table>
</div>
{% else %}
<p>No variants are available.</p>
{% endif %}

<div class="addvar_button">
  <p>
    <button class="btn btn-primary">Create new variant</button>
  </p>
</div>

<div class="addvar_form">
  <form action="{% url 'variants:new' %}" method="post">
    {% csrf_token %}
    Gene: <input type="text" name="gene" /><br />
    Reference amino acid (single letter): <input type="text" name="aa_reference" /><br />
    Position (integer): <input type="text" name="aa_position" /><br />
    Variant amino acid (single letter): <input type="text" name="aa_variant" /><br />
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock content %}


{% block extra_js %}
<script>
  $(function() {
    console.log("loading script")
    $(".addvar_form").hide();
    $(".addvar_button").click(function() {
      $(".addvar_button").hide();
      $(".addvar_form").show();
    });
  });
</script>
{% endblock extra_js %}

getevidence/variants/templates/variants/score_display.html
{% load variants_extras %}

{% if score == None %}
  {% for i in 6|get_range %}
    <i class="icon-star-empty getev-lightgray"></i>
  {% endfor %}
{% else %}
  {% if score == -1 %}
    <i class="icon-star getev-red"></i>
    {% for i in 5|get_range %}
    <i class="icon-star-empty getev-gray"></i>
    {% endfor %}
  {% else %}
    <i class="icon-star-empty getev-gray"></i>
    {% for i in score|get_range %}
      <i class="icon-star getev-blue"></i>
    {% endfor %}
    {% for i in score|multiply:"-1"|add:"5"|get_range %}
      <i class="icon-star-empty getev-gray"></i>
    {% endfor %}
  {% endif %}
{% endif %}